import logging
import os

import psycopg
from dotenv import load_dotenv

from backend.workflow.models.state import State

logger = logging.getLogger(__name__)

load_dotenv()


def _get_connection_string():
    POSTGRES_USER = os.getenv("POSTGRES_USER")
    POSTGRES_HOST = os.getenv("POSTGRES_HOST")
    POSTGRES_DB = os.getenv("POSTGRES_DB")
    POSTGRES_PORT = os.getenv("POSTGRES_PORT")

    conn_string = f"postgresql://{POSTGRES_USER}:{POSTGRES_HOST}/{POSTGRES_DB}"
    return conn_string


async def sql_uploader(state: State):
    logger.info("SQL Uploader:")
    conn_string = _get_connection_string()
    try:
        with psycopg.connect(conn_string) as conn:
            RENDER_TABLE = os.getenv("RENDER_TABLE")
            with conn.cursor() as cur:
                # create table
                # client_uuid, query, code_generated, url, public_id
                create_table_query = f"""
                    CREATE TABLE IF NOT EXISTS {RENDER_TABLE}(
                        uuid UUID,
                        query VARCHAR(1000) NOT NULL,
                        code_generated VARCHAR(20000) NOT NULL,
                        url VARCHAR(200),
                        public_id VARCHAR(60),
                        created_at TIMESTAMPTZ,
                        completed_at TIMESTAMPTZ,
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                    );
                """
                cur.execute(create_table_query)
                logger.info("Created table")
                insert_query = f"""
                    INSERT INTO {RENDER_TABLE} (uuid, query, code_generated, url,
                    public_id, created_at, completed_at)
                    VALUES (%s, %s, %s, %s, %s, %s, %s);
                """
                cur.execute(
                    insert_query,
                    (
                        state.uuid,
                        state.query,
                        state.code_generated,
                        state.url,
                        state.public_id,
                        state.created_at,
                        state.completed_at,
                    ),
                )
                logger.info("Inserted record")
    except Exception as e:
        logger.error(e)
        # Do not error out if can't store the record in sqlite, just log
